---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
  image: "argparse-boost:dev"
#  env_file: .env
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity

  app:
    <<: *common
    restart: "no"
    ports:
      - "8000:8000"
